package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cdes generated by hbm2java
 */
@Entity
@Table(name="cdes"
    ,catalog="cours"
)
public class Cdes  implements java.io.Serializable {


     private Integer idCde;
     private Clients clients;
     private Date dateCde;
     private Set<Ligcdes> ligcdeses = new HashSet<Ligcdes>(0);

    public Cdes() {
    }

	
    public Cdes(Clients clients, Date dateCde) {
        this.clients = clients;
        this.dateCde = dateCde;
    }
    public Cdes(Clients clients, Date dateCde, Set<Ligcdes> ligcdeses) {
       this.clients = clients;
       this.dateCde = dateCde;
       this.ligcdeses = ligcdeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cde", unique=true, nullable=false)
    public Integer getIdCde() {
        return this.idCde;
    }
    
    public void setIdCde(Integer idCde) {
        this.idCde = idCde;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_client", nullable=false)
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_cde", nullable=false, length=10)
    public Date getDateCde() {
        return this.dateCde;
    }
    
    public void setDateCde(Date dateCde) {
        this.dateCde = dateCde;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cdes")
    public Set<Ligcdes> getLigcdeses() {
        return this.ligcdeses;
    }
    
    public void setLigcdeses(Set<Ligcdes> ligcdeses) {
        this.ligcdeses = ligcdeses;
    }




}


