package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name="clients"
    ,catalog="cours"
)
public class Clients  implements java.io.Serializable {


     private Integer idClient;
     private Villes villes;
     private String nom;
     private String prenom;
     private String adresse;
     private Date dateNaissance;
     private Set<Cdes> cdeses = new HashSet<Cdes>(0);

    public Clients() {
    }

	
    public Clients(Villes villes, String nom) {
        this.villes = villes;
        this.nom = nom;
    }
    public Clients(Villes villes, String nom, String prenom, String adresse, Date dateNaissance, Set<Cdes> cdeses) {
       this.villes = villes;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.dateNaissance = dateNaissance;
       this.cdeses = cdeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_client", unique=true, nullable=false)
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cp", nullable=false)
    public Villes getVilles() {
        return this.villes;
    }
    
    public void setVilles(Villes villes) {
        this.villes = villes;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="adresse", length=100)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_naissance", length=10)
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clients")
    public Set<Cdes> getCdeses() {
        return this.cdeses;
    }
    
    public void setCdeses(Set<Cdes> cdeses) {
        this.cdeses = cdeses;
    }




}


