package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ligcdes generated by hbm2java
 */
@Entity
@Table(name="ligcdes"
    ,catalog="cours"
)
public class Ligcdes  implements java.io.Serializable {


     private LigcdesId id;
     private Cdes cdes;
     private Produits produits;
     private int qte;

    public Ligcdes() {
    }

    public Ligcdes(LigcdesId id, Cdes cdes, Produits produits, int qte) {
       this.id = id;
       this.cdes = cdes;
       this.produits = produits;
       this.qte = qte;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idCde", column=@Column(name="id_cde", nullable=false) ), 
        @AttributeOverride(name="idProduit", column=@Column(name="id_produit", nullable=false) ) } )
    public LigcdesId getId() {
        return this.id;
    }
    
    public void setId(LigcdesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cde", nullable=false, insertable=false, updatable=false)
    public Cdes getCdes() {
        return this.cdes;
    }
    
    public void setCdes(Cdes cdes) {
        this.cdes = cdes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_produit", nullable=false, insertable=false, updatable=false)
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }

    
    @Column(name="qte", nullable=false)
    public int getQte() {
        return this.qte;
    }
    
    public void setQte(int qte) {
        this.qte = qte;
    }




}


