package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name="produits"
    ,catalog="cours"
)
public class Produits  implements java.io.Serializable {


     private Integer idProduit;
     private String designation;
     private double prix;
     private Integer qteStockee;
     private String photo;
     private Set<Ligcdes> ligcdeses = new HashSet<Ligcdes>(0);

    public Produits() {
    }

	
    public Produits(String designation, double prix) {
        this.designation = designation;
        this.prix = prix;
    }
    public Produits(String designation, double prix, Integer qteStockee, String photo, Set<Ligcdes> ligcdeses) {
       this.designation = designation;
       this.prix = prix;
       this.qteStockee = qteStockee;
       this.photo = photo;
       this.ligcdeses = ligcdeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produit", unique=true, nullable=false)
    public Integer getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(Integer idProduit) {
        this.idProduit = idProduit;
    }

    
    @Column(name="designation", nullable=false, length=50)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="prix", nullable=false, precision=7)
    public double getPrix() {
        return this.prix;
    }
    
    public void setPrix(double prix) {
        this.prix = prix;
    }

    
    @Column(name="qte_stockee")
    public Integer getQteStockee() {
        return this.qteStockee;
    }
    
    public void setQteStockee(Integer qteStockee) {
        this.qteStockee = qteStockee;
    }

    
    @Column(name="photo", length=50)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produits")
    public Set<Ligcdes> getLigcdeses() {
        return this.ligcdeses;
    }
    
    public void setLigcdeses(Set<Ligcdes> ligcdeses) {
        this.ligcdeses = ligcdeses;
    }




}


