package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Utilisateurs generated by hbm2java
 */
@Entity
@Table(name="utilisateurs"
    ,catalog="cours"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Utilisateurs  implements java.io.Serializable {


     private String pseudo;
     private String mdp;
     private String email;
     private String qualite;

    public Utilisateurs() {
    }

	
    public Utilisateurs(String pseudo, String mdp, String email) {
        this.pseudo = pseudo;
        this.mdp = mdp;
        this.email = email;
    }
    public Utilisateurs(String pseudo, String mdp, String email, String qualite) {
       this.pseudo = pseudo;
       this.mdp = mdp;
       this.email = email;
       this.qualite = qualite;
    }
   
     @Id 

    
    @Column(name="pseudo", unique=true, nullable=false, length=50)
    public String getPseudo() {
        return this.pseudo;
    }
    
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }

    
    @Column(name="mdp", nullable=false, length=50)
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    
    @Column(name="email", unique=true, nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="qualite", length=50)
    public String getQualite() {
        return this.qualite;
    }
    
    public void setQualite(String qualite) {
        this.qualite = qualite;
    }




}


