package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendeursVillesId generated by hbm2java
 */
@Embeddable
public class VendeursVillesId  implements java.io.Serializable {


     private int idVendeur;
     private String cp;
     private Date dateDebut;

    public VendeursVillesId() {
    }

    public VendeursVillesId(int idVendeur, String cp, Date dateDebut) {
       this.idVendeur = idVendeur;
       this.cp = cp;
       this.dateDebut = dateDebut;
    }
   


    @Column(name="id_vendeur", nullable=false)
    public int getIdVendeur() {
        return this.idVendeur;
    }
    
    public void setIdVendeur(int idVendeur) {
        this.idVendeur = idVendeur;
    }


    @Column(name="cp", nullable=false, length=5)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }


    @Column(name="Date_debut", nullable=false, length=10)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendeursVillesId) ) return false;
		 VendeursVillesId castOther = ( VendeursVillesId ) other; 
         
		 return (this.getIdVendeur()==castOther.getIdVendeur())
 && ( (this.getCp()==castOther.getCp()) || ( this.getCp()!=null && castOther.getCp()!=null && this.getCp().equals(castOther.getCp()) ) )
 && ( (this.getDateDebut()==castOther.getDateDebut()) || ( this.getDateDebut()!=null && castOther.getDateDebut()!=null && this.getDateDebut().equals(castOther.getDateDebut()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVendeur();
         result = 37 * result + ( getCp() == null ? 0 : this.getCp().hashCode() );
         result = 37 * result + ( getDateDebut() == null ? 0 : this.getDateDebut().hashCode() );
         return result;
   }   


}


