package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendeursVilles generated by hbm2java
 */
@Entity
@Table(name="vendeurs_villes"
    ,catalog="cours"
)
public class VendeursVilles  implements java.io.Serializable {


     private VendeursVillesId id;
     private Vendeurs vendeurs;
     private Villes villes;
     private Date dateFin;

    public VendeursVilles() {
    }

    public VendeursVilles(VendeursVillesId id, Vendeurs vendeurs, Villes villes, Date dateFin) {
       this.id = id;
       this.vendeurs = vendeurs;
       this.villes = villes;
       this.dateFin = dateFin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVendeur", column=@Column(name="id_vendeur", nullable=false) ), 
        @AttributeOverride(name="cp", column=@Column(name="cp", nullable=false, length=5) ), 
        @AttributeOverride(name="dateDebut", column=@Column(name="Date_debut", nullable=false, length=10) ) } )
    public VendeursVillesId getId() {
        return this.id;
    }
    
    public void setId(VendeursVillesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vendeur", nullable=false, insertable=false, updatable=false)
    public Vendeurs getVendeurs() {
        return this.vendeurs;
    }
    
    public void setVendeurs(Vendeurs vendeurs) {
        this.vendeurs = vendeurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cp", nullable=false, insertable=false, updatable=false)
    public Villes getVilles() {
        return this.villes;
    }
    
    public void setVilles(Villes villes) {
        this.villes = villes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_fin", nullable=false, length=10)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


