package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VentesCroisees generated by hbm2java
 */
@Entity
@Table(name="ventes_croisees"
    ,catalog="cours"
)
public class VentesCroisees  implements java.io.Serializable {


     private VentesCroiseesId id;
     private int vente;

    public VentesCroisees() {
    }

    public VentesCroisees(VentesCroiseesId id, int vente) {
       this.id = id;
       this.vente = vente;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nomVendeur", column=@Column(name="nom_vendeur", nullable=false, length=50) ), 
        @AttributeOverride(name="designation", column=@Column(name="designation", nullable=false, length=50) ) } )
    public VentesCroiseesId getId() {
        return this.id;
    }
    
    public void setId(VentesCroiseesId id) {
        this.id = id;
    }

    
    @Column(name="vente", nullable=false)
    public int getVente() {
        return this.vente;
    }
    
    public void setVente(int vente) {
        this.vente = vente;
    }




}


