package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ventes generated by hbm2java
 */
@Entity
@Table(name="ventes"
    ,catalog="cours"
)
public class Ventes  implements java.io.Serializable {


     private VentesId id;
     private Vendeurs vendeurs;
     private Date dateVente;

    public Ventes() {
    }

	
    public Ventes(VentesId id, Vendeurs vendeurs) {
        this.id = id;
        this.vendeurs = vendeurs;
    }
    public Ventes(VentesId id, Vendeurs vendeurs, Date dateVente) {
       this.id = id;
       this.vendeurs = vendeurs;
       this.dateVente = dateVente;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVendeur", column=@Column(name="id_vendeur", nullable=false) ), 
        @AttributeOverride(name="idProduit", column=@Column(name="id_produit", nullable=false) ), 
        @AttributeOverride(name="vente", column=@Column(name="vente", nullable=false) ) } )
    public VentesId getId() {
        return this.id;
    }
    
    public void setId(VentesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vendeur", nullable=false, insertable=false, updatable=false)
    public Vendeurs getVendeurs() {
        return this.vendeurs;
    }
    
    public void setVendeurs(Vendeurs vendeurs) {
        this.vendeurs = vendeurs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_vente", length=10)
    public Date getDateVente() {
        return this.dateVente;
    }
    
    public void setDateVente(Date dateVente) {
        this.dateVente = dateVente;
    }




}


