package entities;
// Generated 7 aot 2018 11:19:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VentesCroiseesId generated by hbm2java
 */
@Embeddable
public class VentesCroiseesId  implements java.io.Serializable {


     private String nomVendeur;
     private String designation;

    public VentesCroiseesId() {
    }

    public VentesCroiseesId(String nomVendeur, String designation) {
       this.nomVendeur = nomVendeur;
       this.designation = designation;
    }
   


    @Column(name="nom_vendeur", nullable=false, length=50)
    public String getNomVendeur() {
        return this.nomVendeur;
    }
    
    public void setNomVendeur(String nomVendeur) {
        this.nomVendeur = nomVendeur;
    }


    @Column(name="designation", nullable=false, length=50)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentesCroiseesId) ) return false;
		 VentesCroiseesId castOther = ( VentesCroiseesId ) other; 
         
		 return ( (this.getNomVendeur()==castOther.getNomVendeur()) || ( this.getNomVendeur()!=null && castOther.getNomVendeur()!=null && this.getNomVendeur().equals(castOther.getNomVendeur()) ) )
 && ( (this.getDesignation()==castOther.getDesignation()) || ( this.getDesignation()!=null && castOther.getDesignation()!=null && this.getDesignation().equals(castOther.getDesignation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNomVendeur() == null ? 0 : this.getNomVendeur().hashCode() );
         result = 37 * result + ( getDesignation() == null ? 0 : this.getDesignation().hashCode() );
         return result;
   }   


}


